# Generated by Django 5.0.4 on 2024-04-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0002_employee_created_at_employee_updated_at_addtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtask',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
